name: oli
favicon: null
layout_spectrum: 0.8597041165921837
typography_spectrum: 0.26229436649009585
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors: []
  brandStrength: 0.48383000446483493
  lightness: 0.9334147081244737
  saturation: 0.8308569935616106
  rhythmicContrast: 0.050830572843551636
purpose: []
